development:
  adapter: postgresql
  database: missed_connections_development

test:
  adapter: postgresql
  database: missed_connections_test

production:
  adapter: postgresql
  database: missed_connections_production
